name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: xvfb-run -a npm ci
        if: runner.os == 'Linux'
      - run: npm ci
        if: runner.os != 'Linux'
      - run: xvfb-run -a npm run lint
        if: runner.os == 'Linux'
      - run: npm run lint
        if: runner.os != 'Linux'
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm test
        if: runner.os != 'Linux'
